#!/bin/sh
set -e

# Check if Docker is not installed
if ! command -v docker > /dev/null 2>&1
then
	# Install Docker
	set -o pipefail
	curl -fsSL get.docker.com | sh || { echo -e "\e[31m[ERROR]\e[0m Failed to install Docker."; return 1; }
fi

# Check if user is not a member of the Docker group
if ! groups "$SUDO_USER" | grep -q "\bdocker\b"
then
	# Add the current user to the Docker group if not already a member
	usermod -aG docker "$SUDO_USER" || { echo -e "\e[31m[ERROR]\e[0m Failed to add user to docker group."; return 2; }
fi
