name: Gitopia Mirror

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to Gitopia mirror
        uses: gitopia/gitopia-mirror-action@v0.5.0
        with:
          gitopiaWallet: "${{ secrets.GITOPIA_WALLET }}"
          remoteUrl: "gitopia://gitopia19g8nt7nyz6kempdjlem9pf2fzjanfzagkzc9qw4expy3xvc67p0sqf9spd/dvpn-node-manager"
          force: true
